### ISSUE TITLE
Add firefox support

### ISSUE THREAD

**Issue by goosmaster** [tcrammond/chrome-pullrequest-templates#13]
I really like the idea of this plugin, sadly there is no alternative for firefox.

**Comment by tcrammond** [comment]
Hi, thanks for your suggestion. I will be getting around to some enhancements to this extension "soon" and will look into Firefox while I'm there.

**Comment by tcrammond** [comment]
[https://addons.mozilla.org/en-GB/firefox/addon/git-pull-request-templates/](https://addons.mozilla.org/en-GB/firefox/addon/git-pull-request-templates/) 🎉
