### ISSUE TITLE
CSS Missing From the Options Page

### ISSUE THREAD

**Issue by dougiefresh49** [tcrammond/chrome-pullrequest-templates#3]
On the latest version (0.1.7), the options page is missing the css.

![screen shot 2016-09-13 at 2 54 54 pm](https://cloud.githubusercontent.com/assets/1434101/18489247/60a396b4-79c2-11e6-9d53-11cd1ca987a7.png)

**Comment by dougiefresh49** [comment]
any updates on this?

**Comment by tcrammond** [comment]
Hi! This is fixed with the latest release. Sorry for taking forever.
