### ISSUE TITLE
Default PR text on Bitbucket

### ISSUE THREAD

**Issue by OBellon** [tcrammond/chrome-pullrequest-templates#4]
Hi,

I'm currently using the templates with Bitbucket, and I realized that sometimes the default text that Bitbucket provides in the PR (commit messages, mainly) disappears. 

So sometimes the template is added to the one that Bitbucket provides, and sometimes overwrites it. I don't know if it happens in Github two.

I have seen the code, and the first behavior was expected. I think that setTimeout is not enough sometimes.

```javascript
setTimeout(function() {
  el.value = el.value + (el.value && el.value.length ? '\r\n' : '') + template;
}, 1000);
``` 

Thank you so much,
Oscar.

**Comment by tcrammond** [comment]
Thanks for your comment, I'll see what I can do 😄
