### ISSUE TITLE
Duplicated template when editing the pull request.

### ISSUE THREAD

**Issue by OBellon** [tcrammond/chrome-pullrequest-templates#5]
Hi again!

I've seen another issue related to the previous one I commented you.

As the default behavior is adding the template to whatever is there, when you try to edit a pull request, you have the template duplicated.

Adding an option in the configuration to decide if the template should overwrite or add the template to whatever is in the textbox would be great.

Thank you so much,
Oscar.

**Comment by kielabokkie** [comment]
I think it shouldn't add or overwrite if there is anything in the text area already

**Comment by OBellon** [comment]
@kielabokkie There is a problem with that: Bitbucket adds a default template with the commit messages, so it has to replace them, but it doesn't have to when you are updating your pull request. That's why I think about looking for '/update' in the url, and if you find it, do not replace anything.
