### ISSUE TITLE
(BUG) Template not populating with latest version of Bitbucket

### ISSUE THREAD

**Issue by jpcaparas** [tcrammond/chrome-pullrequest-templates#7]
Hi @tcrammond,

First off, thanks for creating this Chrome extension. It standardises our team workflow.

At the moment, the template is not loading with Bitbucket's new `textarea` field, which tries to do away with _Preview_ mode and uses a `contenteditable` `<div />` element now.

<img width="1076" alt="screen shot 2017-09-12 at 11 02 24" src="https://user-images.githubusercontent.com/2406808/30300644-e69acd54-97a9-11e7-859e-9043b4fc1bbe.png">

Hopefully you can look into this soon.

Thanks,
JP

**Comment by tcrammond** [comment]
Thanks for reporting this @jpcaparas 

I added support for the new editor and it will be available on the Chrome web store "soon", usually within an hour. It should support both the new and the old editor.
